services:
  backend:
    build: ./server
    ports: 
      - "3000:3000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    
  frontend:
    build: ./client
    ports:
      - "8080:80"
    depends_on:
      - backend
  
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
