services:
  backend:
    image: rushikeshshelar/todoapp-backend:v1
    ports:
      - "3000:3000"
  frontend:
    image: rushikeshshelar/todoapp-frontend:v1
    environment:
      - VITE_API_BASE_URL=http://localhost:3000
    ports:
      - "80:80"
