services:
  backend:
    image: rushikeshshelar/todoapp-backend:v4
    ports:
      - "3000:3000"
  frontend:
    image: rushikeshshelar/todoapp-frontend:v4
    environment:
      - VITE_API_BASE_URL=http://13.232.195.102:3000
    ports:
      - "80:80"
