name: CI (Run Tests and Build)

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test Application

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node jobs
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Cache Server Dependencies (Node Modules)
        uses: actions/cache@v4
        with: 
          path: server/node_modules
          key: ${{ runner.os }}-server-${{ hashFiles('server/package-lock.json') }}
          restore-keys: ${{ runner.os }}-server-

      - name: Install Server Dependencies
        working-directory: server
        run: npm install

      - name: Run Backend Tests
        working-directory: server
        run: npm run test

      - name: Cache Client Dependencies (Node Modules)
        uses: actions/cache@v4
        with: 
          path: client/node_modules
          key: ${{ runner.os }}-client-${{ hashFiles('client/package-lock.json') }}
          restore-keys: ${{ runner.os }}-client-

      - name: Install Client Dependencies
        working-directory: client
        run: npm install

      - name: Build Frontend
        working-directory: client
        run: npm run build

# Upload the build artifacts for further use in other jobs or workflows (not used in this workflow)
      - name: Upload Buid Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: client/dist

      