name: CD-Backend (Push Backend Docker Image)

on:
  workflow_call:
    secrets:
      DOCKER_ACCESS_TOKEN:
        required: true
  workflow_dispatch:
    secrets:
      DOCKER_ACCESS_TOKEN:
        required: true

jobs:
  docker-push-server:
    runs-on: ubuntu-latest
    name: Push Backend Docker Image

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and Tag Backend (Server) Docker Image
        run: |
         docker build -t ${{ vars.DOCKER_USERNAME }}/todoapp-backend:v4 ./server

      - name: Push backend image
        run: |
          docker push ${{ vars.DOCKER_USERNAME }}/todoapp-backend:v4