name: CD (Build and Push Docker Image)

on:
  workflow_call:

jobs:
  docker-push:
    runs-on: ubuntu-latest
    name: Build and Push Docker Images

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and Tag Backend (Server) Docker Image
        run: |
         docker build -t ${{ vars.DOCKER_USERNAME }}/todoapp-backend:v3 ./server

      - name: Build and Tag Frontend (Client) Docker Image
        run: |
          docker build --build-arg VITE_API_BASE_URL=http://13.235.100.32:3000 -t ${{ vars.DOCKER_USERNAME }}/todoapp-frontend:v2 ./client

      - name: Push backend image
        run: |
          docker push ${{ vars.DOCKER_USERNAME }}/todoapp-backend:v3

      - name: Push frontend image
        run: |
          docker push ${{ vars.DOCKER_USERNAME }}/todoapp-frontend:v3
