name: CI Pipeline

on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node jobs
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Run Docker Compose
        run: docker-compose up --build -d

      - name: Wait for services
        run: sleep 10

      - name: Run Backend Tests
        run: docker exec server npm run test

      