name: CI Pipeline

on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node jobs
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Run Docker Compose
        run: docker compose up -d --build 

      - name: Wait for services
        run: sleep 10

      
      - name: Wait for Backend to be Ready
        run: sleep 10

      - name: Test Backend Endpoint
        run: |
          curl -f http://localhost:5000/todos || exit 1

      