name: CI (Run Tests and Build)

on:
  workflow_call:
  workflow_dispatch:

jobs:
  backend-test:
    runs-on: ubuntu-latest
    name: Test Backend Application

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node jobs
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Cache Server Dependencies (Node Modules)
        uses: actions/cache@v4
        with: 
          path: server/node_modules
          key: ${{ runner.os }}-server-${{ hashFiles('server/package-lock.json') }}
          restore-keys: ${{ runner.os }}-server-

      - name: Install Server Dependencies
        working-directory: server
        run: npm install

      - name: Run Backend Tests
        working-directory: server
        run: npm run test