name: CI Pipeline (Run Tests and Build)

on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test Application
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node jobs
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Server Dependencies
        working-directory: server
        run: npm install

      - name: Run Backend Tests
        working-directory: server
        run: npm run test

      - name: Install Client Dependencies
        working-directory: client
        run: npm install

      - name: Build Frontend
        working-directory: client
        run: npm run build

      