name: Deploy (Pull and Restart Docker Containers)

on:
  workflow_call:
    secrets:
      EC2_HOST:
        required: true
      EC2_USERNAME:
        required: true
      EC2_KEY:
        required: true

jobs: 
  build-push-deploy:
    runs-on: ubuntu-latest
    name: Test, Build, Push Docker Images and Deploy to EC2

    steps:
      - name: Copy docker-compose to EC2 (scp)
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          source: "docker-compose.yml"
          target: "~/todoapp/"

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/todoapp/
            sudo docker-compose pull
            sudo docker-compose down
            sudo docker-compose up -d


      