name: CI / CD Pipeline (Run Tests, Build, Push Docker Images and Deploy to EC2)

on: 
  push:
    branches: [main]

jobs:
  ci: 
    uses: ./.github/workflows/ci.yaml

  cd:
    needs: ci
    uses: ./.github/workflows/cd.yaml

  deploy:
    needs: cd
    uses: ./.github/workflows/deploy.yaml
    
