name: CI/CD Workflow Pipeline

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  v1-ci:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit

  v1-cd:
    uses: ./.github/workflows/cd.yaml
    secrets: inherit
    needs: v1-ci

  v2-ci:
    uses: ./.github/workflows/v2-ci.yaml
    secrets: inherit

  v2-cd:
    uses: ./.github/workflows/v2-cd.yaml
    secrets: inherit
    needs: v2-ci

  deploy:
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    needs: 
      - v1-cd
      - v2-cd
  