name: CI/CD Workflow Pipeline

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-frontend:
    uses: ./.github/workflows/ci-frontend.yaml
    secrets: inherit

  ci-backend:
    uses: ./.github/workflows/ci-backend.yaml
    secrets: inherit

  cd-frontend:
    uses: ./.github/workflows/cd-frontend.yaml
    secrets: inherit
    needs: ci-frontend

  cd-backend:
    uses: ./.github/workflows/cd-backend.yaml
    secrets: inherit
    needs: ci-backend

  deploy:
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    needs: 
      - cd-frontend
      - cd-backend
  