name: CI/CD Workflow Pipeline

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit

  cd:
    uses: ./.github/workflows/cd.yaml
    secrets: inherit
    needs: ci

  deploy:
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    needs: cd
  