name: CI/CD Workflow Pipeline

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    uses: ./.github/workflows/v2-non-linear/ci.yaml
    secrets: inherit

  cd:
    uses: ./.github/workflows/v2-non-linear/cd.yaml
    secrets: inherit
    needs: ci

  deploy:
    uses: ./.github/workflows/v2-non-linear/deploy.yaml
    secrets: inherit
    needs: cd
  